POST http://smear-backend.test/api/v1/users
Content-Type: application/json

{
  "first_name": "Gerardo",
  "last_name": "DeBlasio",
  "email": "gerardo.dbl@gmail.com",
  "privacy": true,
  "password": "password",
  "password_confirmation": "password",
  "avatar": {
    "id": 1
  }
}